### ISSUE TITLE
Annotations not saving properly to backend 

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1985]
A couple users have reported problems saving comments. I noticed that when a new tab is open and a category is added, if I refresh the other tab with the same doc open, the category does not appear.

Investigate what is happening and if/how all these errors are related.

![image](https://cloud.githubusercontent.com/assets/4042181/26219188/d73c436c-3bdb-11e7-8012-f8153e7d277b.png)

**Comment by NickHeiner** [comment]
@abbyraskin where did that screenshot come from? What did the user do to elicit that?

**Comment by abbyraskin** [comment]
@tejans24 provided the screenshot -- @tejans24 can you elaborate? i believe this happened specifically when attempting to add a tag from a new tab. the a few users have mentioned their comments/other annotations aren't saving (in a new tab or just in general), but have had trouble reproducing.

**Comment by tejans24** [comment]
@abbyraskin @NickHeiner This looks like it might have been fixed or only happens user special cases. I can't seem to reproduce this issue locally as well.

**Comment by abbyraskin** [comment]
per a user's feedback, this is still happening, at least in IE.

**Comment by abbyraskin** [comment]
Closing this out, as we're unable to reproduce the error and it hasn't happened again recently.
