### ISSUE TITLE
Intake | End Product Description is nil

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9623]
As reported in https://github.com/department-of-veterans-affairs/appeals-support/issues/4131 it is possible for the `end_product_description` value to be `nil` on a RAMP Review.

![image](https://user-images.githubusercontent.com/44010416/52745029-226d9c80-2fac-11e9-8d87-3302d2b6fc33.png)

## Acceptance criteria

* When an End Product Establishment description is nil, do not display the `Established EP` message on RAMP complete screen.

## Technical notes

* It's not clear if a `nil` description is valid from a business perspective. This will require some investigation. In the support ticket cited above, the data all looked correct in VBMS and VACOLS.

**Comment by leikkisa** [comment]
There was a RAMP Election successfully processed for this Vet on 2018-03-15, a RAMP Refiling on 2019-02-12.  All other intakes attempted on this Veteran have had errors, mostly no_active_appeals.  So the user shouldn't have even gotten to this page in the first place.

The code looks pretty good to me, but our tests for it aren't very good so I think that is a good place to start.

**Comment by leikkisa** [comment]
I'm finding that the Ramp Elections for this user on that day that are missing an end_product_description are either canceled or have an error of "connected_preexisting_ep". If there's connected_preexisting_ep, there is a still a RampElection that says it was established, and there's no End Product Establishment, but if you call End Product Establishment on that Ramp Election it creates a temporary one. However, that EPE doesn't have an End Product, so when it tries to get the description it returns nil.

I think it's bad for reporting that we're reporting the errored intakes as established Ramp Elections.

**Comment by leikkisa** [comment]
Confirmed that the current code shouldn't have this problem, because it's saving the EndProductEstablishment to the database.

**Comment by pkarman** [comment]
By "current code" you mean the problem was fixed sometime after the reported bug?

**Comment by leikkisa** [comment]
#### Validation instructions
- Create a RAMP Election Opt-in for a Veteran
- Create another RAMP election Opt-in for that Veteran (this should cause the End Product to be connected)
- On the confirmation page for the second RAMP Election Opt-In, see if there is an end_product description

**Comment by Sjones352** [comment]
@leikkisa do you have any file number that has a RAMP-opt-election document in VBMS. I actually added a document on this file but I still get this error. Can you provide me a file if you have one that is eligible to participate in RAMP? 

![Screen Shot 2019-04-12 at 10.14.07 AM.png](https://images.zenhubusercontent.com/5b8fddd1b2cc7b6c78ece9f9/c8730517-9016-457c-b383-1bcbcff39c47)

**Comment by leikkisa** [comment]
I _think_ this one might work: 700032068

**Comment by leikkisa** [comment]
If it does work, here's a script to help find more in the future:
```
LegacyAppeal.last(100).select{|la| la.compensation? && la.active? && la.eligible_for_ramp? && la.veteran&.valid?(:bgs)}.map{|la| la.veteran.file_number}
```

And we'd change the .last(100) part as needed.  I only got 5 out of the 100:
["700032068", "700032068", "700034543", "700060390", "700060392"]

**Comment by Sjones352** [comment]
First aRAMP Election Opt-in for a Veteran created

<img width="1287" alt="Screen Shot 2019-04-23 at 8 05 47 PM" src="https://user-images.githubusercontent.com/23080951/56623700-5ba53700-6603-11e9-889f-850e809e642b.png">

**Comment by Sjones352** [comment]
@leikkisa  I keep getting this error whenever I try this file 700060392 that I had orginally created the first  RAMP Election Opt-in. Do I need to clear the first RAMP I had created and try again?
<img width="1057" alt="Screen Shot 2019-04-29 at 3 53 04 PM" src="https://user-images.githubusercontent.com/23080951/56922729-eb7d3200-6a96-11e9-964c-f0f5294eb1fc.png">

**Comment by leikkisa** [comment]
Oh, I'm sorry I didn't think about that. The RAMP opt-in election closes all of the eligible legacy appeals for the Veteran (and opts them into RAMP).  I re-opened the legacy appeal without canceling the end product, so hopefully it works on the second time around.

**Comment by Sjones352** [comment]
Nope I still get the same error. We might need to work through this one together.

**Comment by leikkisa** [comment]
Validated:

![Screen Shot 2019-06-17 at 3.32.24 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/71b07193-32a0-45ba-a9f7-b478a6991bd2)
